### ISSUE TITLE
Unknown option: '--changeDetection'

### ISSUE THREAD

**Issue by vdias38** [ionic-team/angular-toolkit#177] opened 2019-08-28 00:41 UTC
Hi,

I can't use changeDetection option with component generator, returns `Unknown option`

```
$ ionic info

Ionic:

   Ionic CLI                     : 5.2.6 (/Users/victor.dias/.nvm/versions/node/v12.6.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.8.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.6.0 (/Users/victor.dias/.nvm/versions/node/v12.6.0/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
$ ng g c items/components/item-headline --changeDetection=OnPush -d
Unknown option: '--changeDetection'
```

**Comment by dwieeb** [comment] 2019-08-30 15:52
Duplicate of https://github.com/ionic-team/angular-toolkit/issues/94

**Closed by dwieeb** 2019-08-30 15:52 UTC
Labels: bug

**Comment by vdias38** [comment] 2019-08-30 16:19
Hi @dwieeb the issue #94 concerns same option (change-detection) must is not the same, as the option is known on #94 (maybe a previous version) but is unknown here. 
But of course fixing #94 should guarantee the fix of this one...

**Comment by dwieeb** [comment] 2019-08-30 16:29
Thanks for following up! I left a note in the other issue about it.
